[cd]
  command = "/usr/local/bin/fish"

[diff]
  command = "nvim"
  args = ["-d", "{{ .Destination }}", "{{ .Target }}"]

[merge]
  command = "nvim"
  args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
